# Generated by Django 4.2.13 on 2024-06-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Files", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="author",
            new_name="name",
        ),
    ]
