# Generated by Django 4.2.13 on 2024-06-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Files", "0002_rename_author_files_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("nome", models.CharField(max_length=100)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="files",
            name="content",
        ),
        migrations.AddField(
            model_name="files",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Files.category",
            ),
        ),
    ]
